apiVersion: batch/v1
kind: CronJob
metadata:
  name: graphhopper-graph-cache-builder
spec:
  schedule: "0 8,20 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: graphhopper-graph-cache-builder
            image: ghcr.io/bikehopper/graphhopper-graph-cache-builder@sha256:2d4362f145770cfb36af5c457621facdde98606ab9f5d8b845b2a43c8e858ee6
            resources:
              requests:
                memory: "16Gi"
                cpu: "6000m"
            envFrom:
            - secretRef:
                name: minio-graphhopper-staging
            - secretRef:
                name: api-511
            env:
            - name: GEOFABRIK_PATH
              value: /north-america/us/california/norcal-latest.osm.pbf
            - name: OSM_PBF_FILE_NAME
              value: current-norcal-latest.osm.pbf
            - name: API_511_PATH
              value: /transit/datafeeds?operator_id=RG
            - name: API_511_FILE_NAME
              value: current-GTFSTransitData_RG.zip
            - name: BUCKET_NAME
              value: bikehopper-graphhopper
            - name: MINIO_HOST
              value: minio
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullSecrets:
          - name: dockerconfigjson-github-com
          restartPolicy: Never
